
#produtos

#POST https://sistemshop-production.up.railway.app/produto
POST http://localhost:3333/produto
Content-Type: application/json

{
    "nome": "infermeira",
    "descricao": "um gel muito bom",
    "categoria_id": 3,
    "itens": [{
        "nota_id": 1,
        "tamanho": "15.3cm",
        "cor": "azul",
        "marca": "rex",
        "codigo_barras": "12837192837",
        "valor_compra": 12.50,
        "valor_venda": 20.00,
        "lucro": 7.50
    }]
    

}
###
#GET https://sistemshop-production.up.railway.app/produtos
GET http://localhost:3333/produtos?itens=estoque&nome=
###
PUT https://sistemshop-production.up.railway.app/produto/afd7014d-8d78-4f9c-b97e-2692613129db
Content-Type: application/json
{
    "titulo": "video02",
    "descricao": "adfasdasd",
    "duracao": 120
}
###
DELETE http://localhost:3333/produto/18

###
DELETE http://localhost:3333/produto/item/183

# Notas

###
POST http://localhost:3333/nota
Content-Type: application/json

{
    "codigo": "12346",
    "quantidade": 15,
    "valor_total": 150.5,
    "data": "2025-09-11 23:39:19.585 +00:00"
}
###
GET http://localhost:3333/notas
###
PUT http://localhost:3333/nota/3
Content-Type: application/json

{
    "fornecedor": "Gato Preto"
}

###
DELETE http://localhost:3333/nota/3

# Categorias

###
POST http://localhost:3333/categoria
Content-Type: application/json

{
    "nome": "Acessorios",
    "descricao": "asdasad"
}
###
GET http://localhost:3333/categorias

###
PUT http://localhost:3333/categoria/2
Content-Type: application/json

{
    "nome": "Gel GA"
}

###
DELETE http://localhost:3333/categoria/1

# Cliente

###
POST http://localhost:3333/cliente
Content-Type: application/json

{
    "nome": "Marcelo",
    "email": "romafe123@gmail.com",
    "telefone": "(13) 99741-1234",
    "endereco": "aksldjadaasdakjca"
}
###
GET http://localhost:3333/clientes


# Venda

###
POST http://localhost:3333/venda
Content-Type: application/json

{
    "cliente_id": 1,
    "itensVendidos": [
        {"itemEstoque_id": 15, "valor_produto": 45.00}
    ],
    "status": "finalizada"
}

###
GET http://localhost:3333/vendas


# Nota Venda

###
POST http://localhost:3333/notaVenda
Content-Type: application/json

{
    "venda_id": 3,
    "codigo": "52346",
    "valor_nota": 150.5,
    "forma_pagamento": "cartão"
}

###
GET http://localhost:3333/notasVendas


# Conta

###
POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "superUser@gmail.com",
    "senha": "super432"
}

###
POST http://localhost:3333/cadastrar-conta
Content-Type: application/json

{
    "nome": "Admin",
    "email": "superUser@gmail.com",
    "senha": "super432",
    "cargo": "Adm"
}


###
POST http://localhost:3333/register
Content-Type: application/json

{
    "nome": "jorge",
    "email": "jorge@gmail.com",
    "senha": "jerg"
}

###
GET http://localhost:3333/contas

###
GET http://localhost:3333/pendentes

###
PUT http://localhost:3333/aprovar/3

###
DELETE http://localhost:3333/negar/2

















