
#POST https://sistemshop-production.up.railway.app/produto
POST http://localhost:3333/produto
Content-Type: application/json

{
    "nome": "gel skdjas",
    "descricao": "um gel muito bom",
    "img": "https://img.freepik.com",
    "categoria_id": 1,
    "itens": [{
        "nota_id": 1,
        "tamanho": "12.3cm",
        "cor": "rosa",
        "marca": "gal",
        "codigo_barras": "12837192837",
        "valor_compra": 12.50,
        "valor_venda": 20.00,
        "lucro": 7.50
    }]
    

}

###
POST http://localhost:3333/nota
Content-Type: application/json

{
    "codigo": "52346",
    "quantidade": 10,
    "valor_total": 150.5,
    "data": "2025-09-11 23:39:19.585 +00:00"
}

###
POST http://localhost:3333/categoria
Content-Type: application/json

{
    "nome": "Fantasias",
    "descricao": "asdasad"
}
###
POST http://localhost:3333/cliente
Content-Type: application/json

{
    "nome": "Rosangela",
    "email": "romafe@gmail.com",
    "telefone": "(13) 99741-1234",
    "endereco": "aksldjasdakjca"
}
###
POST http://localhost:3333/venda
Content-Type: application/json

{
    "cliente_id": 1,
    "itensVendidos": [
        {"itemEstoque_id": 4, "valor_produto": 25.00},
        {"itemEstoque_id": 5, "valor_produto": 30.00},
        {"itemEstoque_id": 6, "valor_produto": 15.00}
    ],
    "status": "finalizada"
}

###
POST http://localhost:3333/notaVenda
Content-Type: application/json

{
    "venda_id": 4,
    "codigo": "52346",
    "valor_nota": 150.5,
    "forma_pagamento": "cartão"
}

###
#GET https://sistemshop-production.up.railway.app/produtos
GET http://localhost:3333/produtos?itens=vendidos


###
GET http://localhost:3333/notas

###
GET http://localhost:3333/categorias

###
GET http://localhost:3333/clientes
###
GET http://localhost:3333/vendas
###
GET http://localhost:3333/notasVendas

###
PUT https://sistemshop-production.up.railway.app/produto/afd7014d-8d78-4f9c-b97e-2692613129db
Content-Type: application/json

{
    "titulo": "video02",
    "descricao": "adfasdasd",
    "duracao": 120
}

###
PUT http://localhost:3333/nota/3
Content-Type: application/json

{
    "codigo": "4",
    "quantidade": 6,
    "valor_total": 106.5,
    "data": "2025-09-11 23:39:19.585 +00:00"
}

###
PUT http://localhost:3333/categoria/2
Content-Type: application/json

{
    "nome": "Gel GA"
}

###
DELETE https://sistemshop-production.up.railway.app/produto/5

###
DELETE http://localhost:3333/nota/3


###
DELETE http://localhost:3333/categoria/1